name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild -configuration Release
          hdiutil create -volname Caesar3Unpacker -srcfolder build/Release/Caesar3Unpacker.app -ov -format UDZO Caesar3Unpacker.dmg
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Caesar3Unpacker.dmg
          path: Caesar3Unpacker.dmg
